#!/bin/bash

TICKETS_DIR="${HOME}/.tickets/"

__push() {
	git -C $TICKETS_DIR push -u origin master &> /dev/null
}

__commit() {
	git -C $TICKETS_DIR add --all &> /dev/null
	git -C $TICKETS_DIR commit -am"$1" > /dev/null
}

__pull() {
	git -C $TICKETS_DIR pull  > /dev/null
}

__info() {
	# $1 - filename
	echo ""
}

sync() {
	__pull;
	__push;
}

new() {
	__pull;
	id=`ls -r ${TICKETS_DIR} | sed '1q' | awk '{ printf "%03d",$1+1 }'`
	if [ -z "$id" ];then
      		id='001'
	fi
	echo "ticket $id"
	echo -n 'name:'
	read name
	echo -n 'status:'
	read status
	echo -n 'assigned_to:'
	read assigned_to
	echo -n 'estimated_time[hh:mm]:'
	read estimated_time
	echo -n 'time_spent[hh:mm]:'
	read time_spent
	echo -n 'description:'
	read description
	echo "name:$name
status:$status
assigned_to:$assigned_to
estimated_time:$estimated_time
time_spent:$time_spent
description:$description" > $TICKETS_DIR/$id

	__commit "added $id";
	__push;
	echo "ticket $id created"
}

show() {
	cat "$TICKETS_DIR$1"
}

init() {
	mkdir $TICKETS_DIR
	git -C $TICKETS_DIR init > /dev/null
	git -C $TICKETS_DIR remote add origin $1 > /dev/null
	echo 'done'
}

list() {
	grep -l "status:$1" $TICKETS_DIR* | awk 'BEGIN {FS="/"} { print $NF }'
}

count() {
	grep -r "status:$1" ${HOME}/.tickets/* | wc -l
}

open() {
	awk 'BEGIN {FS=":";OFS=":"} $1 != "status" { print } $1 == "status" { print $1,"open" }' $TICKETS_DIR/$1 > /tmp/$1
	cp /tmp/$1 $TICKETS_DIR/$1
	rm /tmp/$1

	__commit "opened $1";
	__push;
	echo "ticket $1 opened"
}

close() {
	awk 'BEGIN {FS=":";OFS=":"} $1 != "status" { print } $1 == "status" { print $1,"closed" }' $TICKETS_DIR/$1 > /tmp/$1
	cp /tmp/$1 $TICKETS_DIR/$1
	rm /tmp/$1

	__commit "closed $1";
	__push;
	echo "ticket $id closed"
}

assign() {
	echo $1
	echo $2
	awk "BEGIN {FS=\":\";OFS=\":\"} \$1 != \"assigned_to\" { print } \$1 == \"assigned_to\" { print \$1, \"$2\" }" $TICKETS_DIR/$1 > /tmp/$1
	cp /tmp/$1 $TICKETS_DIR/$1
	rm /tmp/$1
	
	__commit "assgned $1 to $2";
	__push;
	echo "assgned $1 to $2"
}

log() {
	git -C $TICKETS_DIR log
}

help() {
	echo 'tic init [origin] - initialize .tickets repository in our home folder to origin
tic count [open/closed] - prints number of open and closed tickets
tic new - new ticket
tic show [ticnum] - show ticket
tic list [open/closed] - prints list of open/closed ticketnumbers
tic open [ticnum] - opens ticket
tic close [ticnum] - closes ticket
tic assign [ticnum] [person] - ..
tic log - shows history of changes
tic sync - synces with origin'
}

case $1 in
	'init' ) init $2;;
	'count' ) count $2;;
	'new' ) new;;
	'sync' ) sync;;
	'show' ) show $2;;
	'list' ) list $2;;
	'open' ) open $2;;
	'assign' ) assign $2 $3;;
	'log' ) log;;
	'close' ) close $2;;
	'help' ) help;;
	* ) exit;;
esac

